// after modifying
const {
    maritalStatus,
    gender,
    applicationNo,
    fullName,
    date,
    passportNo,
    placeOfIssue,
    dateOfIssue,
    dateOfBirth,
    religion,
    qualification,
    city,
    woreda,
    phoneNo,
    visaNo,
    sponsorId,
    sponsorAddress,
    nationalId,
    email,
    fileNo,
    wakala,
    signedOn,
    biometricId,
    sponsorName,
    sponsorPhone,
    houseNo,
    agent,
    sponsorArabic,
    visaType,
    contractNo,
    stickerVisaNo,
    currentNationality,
    laborId,
    relativeName,
    relativePhone,
    relativeCity,
    relativeWoreda,
    relativeGender,
    addressRegion,
    relativeKinship,
    subcity,
    relativeHouseNo,
    relativeBirthDate,
    contactPerson2,
    cocCenterName,
    certificateNo,
    contactPhone2,
    passportType,
    placeOfBirth,
    dateOfExpiry,
    occupation,
    region,
    certifiedDate,
    medicalPlace,
    twoPhotographs,
    idCard,
    relativeIdCard,
    english,
    experienceAbroad,
    worksIn,
    height,
    referenceNo,
    ironing,
    sewing,
    babysitting,
    carCare,
    cleaning,
    washing,
    cooking,
    arabic,
    salary,
    numberOfChildren,
    weight,
    remark,
  } = req.body;
  // SQL Query to Insert into DB
  const sql = `
    INSERT INTO applications (
      maritalStatus, gender, applicationNo, fullName, date, passportNo,
      placeOfIssue, dateOfIssue, dateOfBirth, religion, qualification, city, woreda, phoneNo,
      visaNo, sponsorId, sponsorAddress, nationalId, email, fileNo,
      wakala, signedOn, biometricId, sponsorName, sponsorPhone, houseNo, agent,
      sponsorArabic, visaType, contractNo, stickerVisaNo, currentNationality, laborId,
      relativeName, relativePhone, relativeCity, relativeWoreda, relativeGender, addressRegion,
      relativeKinship, subcity, relativeHouseNo, relativeBirthDate, contactPerson2,
      cocCenterName, certificateNo, contactPhone2, passportType, placeOfBirth, dateOfExpiry,
      occupation, region, certifiedDate, medicalPlace, twoPhotographs, idCard,
      relativeIdCard, english, experienceAbroad, worksIn, height, referenceNo,
      ironing, sewing, babysitting, carCare, cleaning, washing, cooking, arabic,
      salary, numberOfChildren, weight, remark, regularPhoto, fullSizePhoto, passportPhoto
    ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
  `;
  const values = [
    maritalStatus, gender, applicationNo, fullName, date, passportNo,
    placeOfIssue, dateOfIssue, dateOfBirth, religion, qualification, city, woreda, phoneNo,
    visaNo, sponsorId, sponsorAddress, nationalId, email, fileNo,
    wakala, signedOn, biometricId, sponsorName, sponsorPhone, houseNo, agent,
    sponsorArabic, visaType, contractNo, stickerVisaNo, currentNationality, laborId,
    relativeName, relativePhone, relativeCity, relativeWoreda, relativeGender, addressRegion,
    relativeKinship, subcity, relativeHouseNo, relativeBirthDate, contactPerson2,
    cocCenterName, certificateNo, contactPhone2, passportType, placeOfBirth, dateOfExpiry,
    occupation, region, certifiedDate, medicalPlace, twoPhotographs, idCard,
    relativeIdCard, english, experienceAbroad, worksIn, height, referenceNo,
    ironing, sewing, babysitting, carCare, cleaning, washing, cooking, arabic,
    salary, numberOfChildren, weight, remark, regularPhoto, fullSizePhoto, passportPhoto
  ];
